### ISSUE TITLE
NPC channel not working

### ISSUE THREAD

**Issue by killer926** [OTCv8/otclientv8#39]
When you talk to any NPC their channel doesn't pop and doesn't show the conversation so you can't continue talking to the npc, if you move to the channel by yourself you can "trade" but still nothing from the npc in the conversation.

**Comment by armadaazteca** [comment]
@OTCv8 This happened tome on a  9.61 server (using TFS 0.2.14). I was able to fix it in otc with this: 
https://github.com/armadaazteca/otclient/commit/8d9681a6e5b21760f3c31240b49459228f1dbd4f#diff-0872ce22758ab2fad9884a58da53302dR90-R91

I didn't add the logic to only apply it to 9.60/9.61. I don't think it applies for any other version, I just know about these 2 because of the sources here

https://github.com/Armada-Azteca/ArmadaAztecaServer/blob/master/tfs_0.2.14/src/const.h#L185

Would it be possible to include this in otcv8?

**Comment by OTCv8** [comment]
Fixed in 2.4
